# Generated by Django 4.2.4 on 2023-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя в ТГ'),
        ),
    ]
