# Generated by Django 4.2.4 on 2023-11-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место — место, в котором необходимо выполнять привычку.', max_length=100, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время — время, когда необходимо выполнять привычку.', verbose_name='Время')),
                ('action', models.TextField(help_text='Действие — действие, которое, представляет из себя, привычка.', verbose_name='Действие')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Периодичность (по умолчанию ежедневная) — периодичность выполнения привычки для напоминания в днях.', verbose_name='Периодичность выполнения')),
                ('time_to_complete', models.IntegerField(help_text='Время на выполнение — время, которое предположительно потратит пользователь на выполнение привычки.', verbose_name='Время на выполнение, в секундах')),
                ('pleasant_habit', models.BooleanField(default=False, help_text='Признак приятной привычки — привычка, которую можно привязать к выполнению полезной привычки.', verbose_name='Признак приятной привычки')),
                ('reward', models.TextField(blank=True, help_text='Вознаграждение — чем пользователь должен себя вознаградить после выполнения.', null=True, verbose_name='Вознаграждение за выполнение действия')),
                ('is_public', models.BooleanField(default=False, help_text='Признак публичности — привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.', verbose_name='Признак публичности привычки')),
                ('last_send', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка напоминания')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь — создатель привычки.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Связанная привычка — привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('pk',),
            },
        ),
    ]
