# Generated by Django 4.2.4 on 2023-11-14 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполнение действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='Время на выполнение, в секундах'),
        ),
    ]
